# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Towards Causal VQA " #- Revealing and Reducing Spurious Correlations by Invariant and Covariant Semantic Editing"
# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
#remote_theme: "mmistakes/minimal-mistakes@4.19.1"
description: Revealing and Reducing Spurious Correlations by Invariant and Covariant Semantic Editing. 
tagline: Revealing and Reducing Spurious Correlations by Invariant and Covariant Semantic Editing 
#description: ""
url: "https://rakshithshetty.github.io" # the subpath of your site, e.g. /blog
baseurl: "/CausalVQA" # the subpath of your site, e.g. /blog
show_downloads: true
show_tagline: true
auth_color: "color:#EFF3D1"
aff_color: "color:#000000"
owner:
    name: Rakshith Shetty
    email: rshetty@mpi-inf.mpg.de
author:
    name: Rakshith Shetty

paper_url: "https://arxiv.org/abs/1912.07538" 
datasetlink: "https://rakshithshetty.github.io/CausalVQA/#dataset"
#plugins:
#    - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
